### PR TITLE
Implement zero-cycle runs

### PR DESCRIPTION
**Pull request by mhovd**
When cycles = 0, IPM will be used to reweight the support points. Support points can be the sobol sequence or the supplied prior.

### CODE REVIEW

**Comment by mhovd** [comment]
Would the code for this be better off in `mod.rs`, or should they be a part of NPAG like now?

**Comment by Siel** [comment]
> Would the code for this be better off in `mod.rs`, or should they be a part of NPAG like now?

I think it should not be in NPAG, because it has nothing to do with the NPAG algorithm. I would  create a new algorithm (zero-run maybe) and call that algorithm if I detect cycles=0

**Comment by Siel** [comment]
Re-weight, NPeval, NPweight. I'm very bad at naming, but let's pick something and we might change it later

**Comment by mhovd** [comment]
Planning to move the output generation to a separate file, e.g. `outputs.rs`, and the zero-cycle algorithm to e.g. `npopt.rs`

**Comment by mhovd** [comment]
Closed as this was implemented differently in #18

**Pull request closed without merging**
