### PR TITLE
Implement option to stop run early

### PR DESCRIPTION
**Pull request by mhovd**
On each cycle of NPAG, the program will check if the file `stop` exists. If it does, the program will stop (prior to the next cycle).
A shortcut was added to the TUI, mapped to `CTRL+D`, which will write the file, leading to a stop.

### CODE REVIEW

**Comment by mhovd** [comment]
@Siel please review the changes to `Config.toml`, where I had to add a dependency for some reason. It may not be necessary.

**Comment by masyamada** [comment]
I didn't look at the code ... because I probably can't read it!!! BUT ...
all you have to do is run CHMAXCYC.BAT, which is already in the run
directory.  It's in windows (COPY instead of cp). but NPAG will
automatically stop at end of next cycle and write out all the output files.

**Comment by mhovd** [comment]
> @mhovd I removed the dependency, but we might need to remove the stop file after the run is done, because it stops all future executions on cycle 1

Yes and no - it NPcore is used correctly, where each run is in an isolated folder, then it doesn't matter.
But when we are testing or the user wants to re-run their model then it needs to go.
I don't see any reason why we should keep it, so might as well delete it.

**Comment by Siel** [comment]
@mhovd I just implemented that, and it's working. I'm going to merge this PR

**Pull request merged**
